# Generated by Django 5.0.6 on 2024-11-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_category_tag_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
