# Generated by Django 5.0.6 on 2024-11-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title2',
        ),
    ]
