# Generated by Django 5.0.6 on 2024-11-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_snippet',
        ),
    ]
