# Generated by Django 5.1.3 on 2024-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemail',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
